#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail
set -o xtrace

readonly TARGET_HOST=abittouchy@192.168.50.74
readonly TARGET_PATH=/home/abittouchy/qm-debs
readonly TARGET_ARCH=armv7-unknown-linux-gnueabihf
readonly SOURCE_PATH=./src-tauri/target/${TARGET_ARCH}/release/bundle/deb

cross build --target armv7-unknown-linux-gnueabihf

#yarn tauri build --target=${TARGET_ARCH}
#rsync ${SOURCE_PATH} ${TARGET_HOST}:${TARGET_PATH}
#ssh -t ${TARGET_HOST} ${TARGET_PATH}
